local M = {}

--- Sets up a synchronized layout to display original code alongside proposed patches via native diffing.
--- @param orig_win integer Window handle where execution started.
--- @param orig_buf integer Buffer handle containing original source files.
--- @param ai_lines table Sequential array containing text lines generated by the LLM response.
--- @param ft string Filetype string configuration extracted from the original buffer context.
--- @param opts table Metadata flags containing information on user selection states.
function M.create_preview(orig_win, orig_buf, ai_lines, ft, opts)
    if not vim.api.nvim_buf_is_valid(orig_buf) then return end

    -- Resilient target window matching to ensure we split the right viewport
    local target_win = orig_win
    if not vim.api.nvim_win_is_valid(target_win) or vim.api.nvim_win_get_buf(target_win) ~= orig_buf then
        target_win = nil
        for _, win in ipairs(vim.api.nvim_list_wins()) do
            if vim.api.nvim_win_get_buf(win) == orig_buf then
                target_win = win
                break
            end
        end
    end
    if not target_win then return end

    -- Compute target replacement bounds using our captured line state
    local orig_lines = vim.api.nvim_buf_get_lines(orig_buf, 0, -1, false)
    local is_range = opts.range > 0
    local start_row = is_range and opts.line1 or opts.invocation_line
    local end_row = is_range and opts.line2 or start_row

    local modified_lines = {}
    -- 1. Dump the entire original file straight into the scratch buffer
    local scratch_buf = vim.api.nvim_create_buf(false, true)
    vim.api.nvim_buf_set_lines(scratch_buf, 0, -1, false, orig_lines)

    -- 2. Define the exact 0-indexed bounds for the AI generated text position
    local api_start = start_row - (is_range and 1 or 0)
    local api_end = end_row

    -- 3. Overwrite the AI generated section
    vim.api.nvim_buf_set_lines(scratch_buf, api_start, api_end, false, ai_lines)

    -- Set remaining buffer options
    vim.api.nvim_set_option_value("filetype", ft, { buf = scratch_buf })
    vim.api.nvim_set_option_value("bufhidden", "wipe", { buf = scratch_buf })

    -- Determine optimal split axis based on target window metrics
    local width = vim.api.nvim_win_get_width(target_win)
    local height = vim.api.nvim_win_get_height(target_win)
    local split_direction = width > (height * 2.2) and "right" or "below"

    -- ASYNC WIN SPAWN: Instantiate the split relative to target_win without entering it
    local scratch_win = vim.api.nvim_open_win(scratch_buf, false, {
        split = split_direction,
        win = target_win,
    })

    -- Apply window options to the necessary windows
    vim.api.nvim_set_option_value("foldenable", true, { scope = "local", win = scratch_win })
    vim.api.nvim_set_option_value("foldlevel", 0, { scope = "local", win = scratch_win })

    -- Repeat the pattern for the target window
    vim.api.nvim_set_option_value("foldenable", true, { scope = "local", win = target_win })
    vim.api.nvim_set_option_value("foldlevel", 0, { scope = "local", win = target_win })

    -- Enable diff mode for both windows
    vim.wo[scratch_win].diff = true
    vim.wo[target_win].diff = true

    -- Ensure diff mode is dropped cleanly when the scratch buffer is closed
    vim.api.nvim_create_autocmd("BufWipeout", {
        buffer = scratch_buf,
        callback = function()
            if vim.api.nvim_win_is_valid(target_win) then
                vim.api.nvim_win_call(target_win, function() vim.cmd("diffoff") end)
            end
        end,
    })
end

return M
